// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt01z82B7Sjbh0iAnHPSCaDlRt6YyE9YQ',
    appId: '1:736273979753:web:786283365d37de4a1f45f8',
    messagingSenderId: '736273979753',
    projectId: 'ctse-plant',
    authDomain: 'ctse-plant.firebaseapp.com',
    storageBucket: 'ctse-plant.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnDePHPX4ibiiKuUCc3lfl5LVtshSmpE',
    appId: '1:736273979753:android:e33610f516a509511f45f8',
    messagingSenderId: '736273979753',
    projectId: 'ctse-plant',
    storageBucket: 'ctse-plant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Khc_ruwRBWIfPMdWvpeH8E6ybuPj8ys',
    appId: '1:736273979753:ios:49c65395b38de8481f45f8',
    messagingSenderId: '736273979753',
    projectId: 'ctse-plant',
    storageBucket: 'ctse-plant.appspot.com',
    iosClientId:
        '736273979753-u51kagh1ppchf43koto8m354rv1pmhbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantShopApp',
  );
}
